In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import  make_classification
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [3]:
x,y=make_classification(n_samples=1000,n_features=20,n_classes=2,random_state=42)

In [4]:
pd.DataFrame(x).head()

0         1         2         3         4         5         6   \
0 -0.669356 -1.495778 -0.870766  1.141831  0.021606  1.730630 -1.251698   
1  0.093372  0.785848  0.105754  1.272354 -0.846316 -0.979093  1.263707   
2 -0.905797 -0.608341  0.295141  0.943716  0.092936  1.370397 -0.064772   
3 -0.585793  0.389279  0.698816  0.436236 -0.315082  0.459505  1.448820   
4  1.146441  0.515579 -1.222895 -0.396230 -1.293508 -0.352428  0.071254   

         7         8         9         10        11        12        13  \
0  0.289305  0.357163 -0.196811  0.829274  0.154850 -0.219970 -0.739137   
1  0.264020  2.411677 -0.960046  0.543479  0.199810  0.288724  0.732492   
2  0.287273 -0.533004 -0.032504 -0.549925 -0.510064 -0.868768 -0.598279   
3  0.505558 -1.440982 -1.134020 -0.241431  1.466783  0.678728 -1.190917   
4  1.239584  1.007133 -1.479444 -0.695695 -0.918127  0.604121  1.068379   

         14        15        16        17        18        19  
0  1.802012  1.634606 -0.938180 -1.267337 -1.276334  1.016643  
1 -0.872002 -1.654887 -1.130204 -0.122709  0.693431  0.911363  
2  0.019832  0.613460 -1.779439  0.830498 -0.737332 -0.578212  
3 -1.442381 -0.929136 -0.221600 -0.346772  0.034246 -1.040199  
4 -0.882271  2.303639 -0.973379  1.259233  0.360015  1.920368

In [5]:
pd.DataFrame(y).head()

0
0  1
1  0
2  1
3  1
4  0

In [6]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

In [7]:
logistic=LogisticRegression()
logistic.fit(x_train,y_train)

LogisticRegression()

In [8]:
y_pred=logistic.predict(x_test)
print(y_pred)

[1 1 0 1 1 0 0 1 1 0 1 1 0 0 1 0 0 1 1 0 1 0 0 0 1 0 1 1 0 1 1 1 1 0 0 0 0
 0 0 0 0 1 0 0 0 0 1 0 1 1 0 0 0 1 1 1 0 0 1 0 1 0 0 1 1 0 1 1 1 0 0 0 0 0
 0 1 0 0 1 0 0 0 0 1 1 1 0 0 0 0 1 0 0 0 1 0 1 0 1 0 1 1 0 0 1 0 1 0 0 0 0
 0 0 1 0 1 1 0 1 0 1 1 0 0 1 1 1 0 0 1 0 1 1 0 1 1 0 1 0 1 0 0 1 1 0 1 1 0
 0 1 1 1 0 0 1 0 1 1 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 0 0 1 1 1 1 0 1 1 0 0 1
 1 0 0 0 1 0 1 0 1 1 1 1 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 0 1 0 1 0 1 0 0 0
 0 0 0 1 1 0 1 1 1 0 0 1 1 0 0 1 1 1 1 1 1 0 1 0 1 0 0 0]


In [9]:
logistic.predict_log_proba(x_test)

array([[-8.67664650e-01, -5.44608374e-01],
       [-1.95921099e+00, -1.51950972e-01],
       [-6.76226107e-01, -7.10359512e-01],
       [-2.02653297e+00, -1.41323564e-01],
       [-2.95324104e+00, -5.35804820e-02],
       [-6.27416226e-02, -2.79993701e+00],
       [-2.50808834e-01, -1.50584899e+00],
       [-1.66832850e+00, -2.08947276e-01],
       [-1.36534721e+00, -2.94763110e-01],
       [-4.11333410e-01, -1.08697800e+00],
       [-2.99183893e+00, -5.14986279e-02],
       [-8.18047721e-01, -5.82128912e-01],
       [-4.38923467e-03, -5.43079422e+00],
       [-6.08367820e-01, -7.85785500e-01],
       [-1.35132576e+00, -2.99615391e-01],
       [-2.04953425e-01, -1.68569960e+00],
       [-6.15588447e-02, -2.81838327e+00],
       [-2.93014244e+00, -5.48674983e-02],
       [-2.04050986e+00, -1.39218885e-01],
       [-6.63785135e-01, -7.23397503e-01],
       [-4.88011844e+00, -7.62511172e-03],
       [-2.50437273e-01, -1.50715351e+00],
       [-5.22219164e-02, -2.97825035e+00],
       [-9.

In [10]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,confusion_matrix,classification_report
score=accuracy_score(y_test,y_pred)
p_score=precision_score(y_test,y_pred)
r_score=recall_score(y_test,y_pred)
cm=confusion_matrix(y_test,y_pred)
cr=classification_report(y_test,y_pred)
print("Accuracy Score:",score)
print("Precision Score:",p_score)
print("Recall Score:",r_score)
print("Confusion Matrix:\n",cm)
print("Classification Report:\n",cr)

Accuracy Score: 0.852
Precision Score: 0.9083333333333333
Recall Score: 0.8074074074074075
Confusion Matrix:
 [[104  11]
 [ 26 109]]
Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.90      0.85       115
           1       0.91      0.81      0.85       135

    accuracy                           0.85       250
   macro avg       0.85      0.86      0.85       250
weighted avg       0.86      0.85      0.85       250



## Hypertuning and Cross Validation

In [11]:
model=LogisticRegression(max_iter=5000)
penalty=['l1','l2','elasticnet']
c_values=[100,10,1,0.1,0.001]
solver=['newton-cg','lbfgs','liblinear','sag','saga']

In [12]:
params=dict(penalty=penalty,C=c_values,solver=solver)

In [13]:
from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold()

In [15]:
from sklearn.model_selection import GridSearchCV
Grid=GridSearchCV(estimator=model,param_grid=params,cv=cv,n_jobs=-1)

In [16]:
Grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(max_iter=5000), n_jobs=-1,
             param_grid={'C': [100, 10, 1, 0.1, 0.001],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']})

In [18]:
import warnings
warnings.filterwarnings('ignore')
Grid.fit(x_train,y_train)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(max_iter=5000), n_jobs=-1,
             param_grid={'C': [100, 10, 1, 0.1, 0.001],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']})

In [19]:
Grid.best_params_

{'C': 0.1, 'penalty': 'l1', 'solver': 'saga'}

In [20]:
y_pred_grid=Grid.predict(x_test)

In [21]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,confusion_matrix,classification_report
score=accuracy_score(y_test,y_pred_grid)
p_score=precision_score(y_test,y_pred_grid)
r_score=recall_score(y_test,y_pred_grid)
cm=confusion_matrix(y_test,y_pred_grid)
cr=classification_report(y_test,y_pred_grid)
print("Accuracy Score:",score)
print("Precision Score:",p_score)
print("Recall Score:",r_score)
print("Confusion Matrix:\n",cm)
print("Classification Report:\n",cr)

Accuracy Score: 0.864
Precision Score: 0.9173553719008265
Recall Score: 0.8222222222222222
Confusion Matrix:
 [[105  10]
 [ 24 111]]
Classification Report:
               precision    recall  f1-score   support

           0       0.81      0.91      0.86       115
           1       0.92      0.82      0.87       135

    accuracy                           0.86       250
   macro avg       0.87      0.87      0.86       250
weighted avg       0.87      0.86      0.86       250

